### ISSUE TITLE
Handling exogenous trends in energy use

### ISSUE THREAD

**Issue by hshaban** [CalTRACK-2/caltrack#105]
from @bkoran:

> It is hard to determine whether energy use was changing over the baseline, and we know that the energy use relationships can be slightly different in different months, especially for residential. That said, I still believe one of the things we should be doing for NMEC projects and programs is looking at trends of energy use over time. Is energy use increasing or decreasing over the baseline period, and by how much? If energy use decreased significantly from the beginning to end of the baseline, should a program pay for that reduction in energy use for which it wasn’t responsible? Evaluation will answer that question, but I don’t think evaluation should be hamstrung by a method that makes it impossible to determine whether energy use was changing over the baseline because of the method alone, much less including the challenge inherent in the data. With separate models for each month, any month-to-month trend cannot be evaluated. It would be slightly better with rolling 3-month models, but only slightly better because of the weighting.

**Comment by steevschmidt** [comment]
Great points. I won't touch the policy issue regarding how energy use changes within the baseline period should be handled (sounds messy), but I can speak to your last point:
> With separate models for each month, any month-to-month trend cannot be evaluated...

The way HEA handles this (residential only): we develop models unique to each month with the primary goal of disaggregating heating and cooling loads. Once we have three [more accurate] loads for each month (heating, cooling and other) we can then see how each load is trending: directly comparing the "other" category from month to month, and normalizing the heating & cooling loads using monthly DDs values using a common baseline temp (e.g. HDD65s).
