### ISSUE TITLE
Clarify cumulative energy savings for Reporting Periods over 12 months

### ISSUE THREAD

**Issue by steevschmidt** [CalTRACK-2/caltrack#110]
If possible we’d like some clarification on the cumulative savings calculation for projects with reporting periods over 12 months. Is the data annualized?

Sections 3.6 and 3.12 of the [methods document](https://github.com/CalTRACK-2/caltrack/blob/a886aa18401def6a11aa98681e3f0518fd790739/docs/methods.rst) describe how to calculate AEU for each period. Section 4.1.2 specifies that “CalTRACK does not explicitly support annualizing results”.  However, our OEE CalTRACK dashboard displays “Cumulative Savings” for kWhs, therms, and MMBTUs, so our question is regarding how this figure calculated.

Example: Assuming a project savings 100 kWh/month after the intervention:
 * After 3 months cumulative savings would be 300 kWhs.
 * After 12 months cumulative savings would be 1200 kWhs.
 * After 15 months… is the cumulative savings **1500** or **1200** kWhs?

We believe the answer for CalTRACK is 1500 kWhs but would like to clarify. 
(HEA uses a rolling 12 month reporting period described in issue #74.)

**Comment by mcgeeyoung** [comment]
You need to look at [Aggregation](http://docs.caltrack.org/en/latest/methods.html#section-4-aggregation). 4.1.1 describes how savings calculations are aggregated. In essence, neither of your answers is correct. If after 12 months you have 1200 kWh of savings, after 15 months your cumulative savings would be 1200 plus whatever you saved in months 13, 14, and 15.

**Comment by steevschmidt** [comment]
Thanks McGee. 
So in my example case of a reduction in electric base load of 100 kWh/month (compared to the baseline period), I believe 24 months after the intervention cumulative savings would be 2400 kWhs.
