### ISSUE TITLE
CalTRACK Working Group Issue: Voluntary Investigations

### ISSUE THREAD

**Issue by jkoliner** [CalTRACK-2/caltrack#132]
### Prerequisites

* [x] Are you opening this issue in the correct repository (caltrack/grid/seat)?
* [x] Did you perform a search of previous Github issues to check if this issue has been previously considered?

### Description

Although our current process prioritizes important issues for CalTRACK, it does not take into account issues which are small and have willing testers. As the barrier to investigation for these issues is lower, we should entertain a secondary mechanism by which an issue is taken up by the Working Group.

I propose that we allow independent testing of minor issues to be conducted by willing testers. They should notify the group before they begin testing.  Once their testing is completed, the working group will vote to add review of their results to the agenda of a given meeting. At that point, they can share results and ask for another party to confirm them.

### Voting on this Process Change

Please vote by commenting on this post. You may vote "Yes" or "No" on this issue.

**Comment by steevschmidt** [comment]
Yes! Hopefully this will enable more & faster improvements to CalTRACK.

**Comment by philngo-recurve** [comment]
Closing stale issue in preparation for new working group
