### ISSUE TITLE
CalTRACK Issue: Increase total HDD/CDD limits to avoid out-of-range balance points

### ISSUE THREAD

**Issue by philngo** [CalTRACK-2/caltrack#133]
### Prerequisites

* [x] Are you opening this issue in the correct repository (caltrack/grid/seat)?
* [x] Did you perform a search of previous Github issues to check if this issue has been previously considered?

**Article reference number in CalTRACK documentation (optional):** 3.2.2.2.2

### Description

I ran across a problematic baseline model fit when running the billing/daily caltrack model in a cool climate. The selected balance points were seemingly beyond the range of the data. The plot below shows the model fit (plotting average billing period temperature against the energy usage during the period), which has an absurdly large cooling coefficient.

![image](https://user-images.githubusercontent.com/2687443/62997117-f7112080-be1b-11e9-9d5a-ce25022585ba.png)

I was able to recreate this behavior on synthetic dataset similar to the above and wrote a script to reproduce the odd result using the OpenEEmeter:

    import eemeter
    import pandas as pd
    import numpy as np

    design_matrix = pd.DataFrame(
        {
            "meter_value": [52, 42, 38, 33, 34, 35, 35, 54, 35, 37, 52, 45, np.nan],
            "temperature_mean": [30, 29, 35, 47, 57, 66, 70, 69, 63, 57, 42, 37, np.nan],
            "n_days_kept": [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, np.nan],
            "cdd_72": [0,  0,  0,  0,  0,  0.09,  0.29, 0.3, 0.1, 0, 0, 0, np.nan],
            "hdd_72": [42, 43, 37, 26, 14, 6, 2, 4, 9, 15, 29, 34, np.nan],
        },
        index=pd.date_range(start='2014-01-01', end='2015-01-01', freq='MS', tz='utc')
    )
    model = eemeter.fit_caltrack_usage_per_day_model(
        design_matrix,
        use_billing_presets=True,
        weights_col='n_days_kept'
    )
    print(design_matrix)
    print(model.model)

This yields the following:

                               meter_value  temperature_mean  n_days_kept  cdd_72  hdd_72
    2014-01-01 00:00:00+00:00         52.0              30.0         31.0    0.00    42.0
    2014-02-01 00:00:00+00:00         42.0              29.0         28.0    0.00    43.0
    2014-03-01 00:00:00+00:00         38.0              35.0         31.0    0.00    37.0
    2014-04-01 00:00:00+00:00         33.0              47.0         30.0    0.00    26.0
    2014-05-01 00:00:00+00:00         34.0              57.0         31.0    0.00    14.0
    2014-06-01 00:00:00+00:00         35.0              66.0         30.0    0.09     6.0
    2014-07-01 00:00:00+00:00         35.0              70.0         31.0    0.29     2.0
    2014-08-01 00:00:00+00:00         54.0              69.0         31.0    0.30     4.0
    2014-09-01 00:00:00+00:00         35.0              63.0         30.0    0.10     9.0
    2014-10-01 00:00:00+00:00         37.0              57.0         31.0    0.00    15.0
    2014-11-01 00:00:00+00:00         52.0              42.0         30.0    0.00    29.0
    2014-12-01 00:00:00+00:00         45.0              37.0         31.0    0.00    34.0
    2015-01-01 00:00:00+00:00          NaN               NaN          NaN     NaN     NaN

    CalTRACKUsagePerDayCandidateModel(model_type='cdd_hdd', formula='meter_value ~ cdd_72 + hdd_72', status='QUALIFIED', r_squared_adj=0.224)

The `cdd_72`, `hdd_72` columns represent average daily period heating/cooling degree days for the 72 degF balance points. The issue appears to be that in this case there is only a very small number of cooling degree days (just over the 20 total degree days per year limit).

I think the root of the problem is that the balance point range gets too close to the “edge” of the data range, which intuitively makes it more likely to get large coefficients like the ones we were getting for this model, highly influenced by very small average daily hdd/cdd effects. 

The CalTRACK limit for total heating/cooling degree days seems really low to me for billing data. I'd argue to test increasing this limit for billing data in particular to 180 HDD/CDD per year (or somewhere near to that range). I picked 180 because that intuitively corresponds roughly to 90 days at 2 heating/cooling degree days., or 60 days with 3 heating/cooling degree days - keeping the balance points away from the edges of the data. That seems more flexible than requiring any single billing period to meet a particular threshold, but that may also be worth exploring.

### Proposed test methodology

1. Create a testing dataset with two years of billing data per site in a variety of climate zones which includes a variety of model fits and a few examples of fits like the above in the first year. The first year will be used to build baseline models and the second year will be used for out-of-sample testing.
2. Build baseline models using a few different total HDD/CDD balance point limits (e.g., 20, 50, 100, 150, 180, 200, 250) and compare the errors these produce when predicting over the second year out-of-sample test dataset.

### Acceptance Criteria

If the best performing heating/cooling degree day limit corresponds with the intuition above and performs better in the out of sample test, consider adopting it instead of the 20 degree day limit.

**Comment by steevschmidt** [comment]
I don't think I'm completely following the example, but would suggest we don't want to remove "valid" CDDs from the analysis by increasing the minimum limits... seems like there may be better approaches. Our internal method (see #121) only selects balance points within the temperature range of the data.

Just curious: Is the plot from a commercial or residential building? I assume the units on the Y-axis are kWh.

**Comment by philngo** [comment]
@steevschmidt Sorry - just saw this comment. This is residential billing data and the units are kWh.

I actually first tried constraining the balance point search range to not fall below the minimum mean temperature and not exceed the maximum mean temperature of any billing period, as I think you are suggesting. This did actually work well for this case, as the selected balance point (72) was higher than the largest mean temperature (70) which was observed. Doing this would almost certainly be better than continuing to use the existing limit of 20 total HDD or CDD, which is so low I think it is almost the same as using 0.  If I remember correctly from my testing, in this example, even the top of the limit range I'm proposing (250 total HDD/CDD) is actually less restrictive (!) than using the billing period temperature means, not more restrictive, as you suggest.

Even considering that, I don't think that the direct temperature mean restriction approach would generalize as well as the min/max total CDD/HDD approach, and here's why: limiting the range by mean temperature can produce unintended results because there are hourly or daily temperatures that exceed the max of the billing period averages.

If the billing/daily methods start using hourly degree days, as has been in discussion and testing already, then I think we will need to revisit these limits anyway.

I think working with HDD/CDD limits rather than mean temperatures makes more sense when we're talking about HDD/CDD as inputs to the regression model. The proposal in #121 is also worth consideration and testing in my view and I think restricting the search range on the min/max mean billing period temperatures makes much more sense for that case, since the model uses them directly.

I'm not quite sure what you mean by "valid" CDDs, but we're really not "removing" CDDs/HDDs at all - in fact I think this proposal helps ensure that we're _not_ getting nonsensical low CDDs/HDDs that result in absurdly high heating/cooling coefficients. However, we _are_ trying to remove non-physical _balance points_ from consideration. As I suggested above, I think this limit is still extremely permissive. Keep in mind (as a way of calibrating the level of the limit I'm proposing) that in the example shown above, we have 7,892 HDDs with a 72 degree balance point over the course of the year, so the current limit of 20 HDD per year is only 0.2% of that total value, and the maximum limit I'm proposing we test is still only 3% of that total value.

All that said, I'm still planning to do an analysis and test of this so that we can compare these results on a reasonable dataset.

**Comment by steevschmidt** [comment]
Thanks for the additional comments Phil. 

> as a way of calibrating the level of the limit I'm proposing ... in the example shown above, we have 7,892 HDDs...

My comments are based on daily energy & weather data analysis, and I'm thinking in particular of cooling energy use in temperate regions with only a few hot spells per year. In those situations, removing even 20 CDDs could result in missing the big AC unit that ran during those 4 really hot days. This can be important to accurate energy savings calculations, especially if the following summer (during the reporting period) had 120 CDDs.

My own home behaves like this. Over the past 12 months we've had only 92 CDDs (base temp 75F) and that corresponded to 360 kWh of cooling load. These small numbers are still important because we're normalizing them.

By "valid CDDs" I just meant CDDs calculated using accurate weather data. What do you mean by "nonsensical low CDDs/HDDs"? Are you assuming the weather data producing a small number of DDs is wrong? If so, I'd think it would affect all DDs, even those above the minimum threshold.

**Comment by philngo** [comment]
All I'm trying to do here is keep the model from overfitting in the majority of cases, which is not to say that it will get every case exactly right. However, keep in mind we are trying a whole range of balance points and looking for the best fit, so those hot spells are not lost from the analysis.

**Comment by philngo** [comment]
In the case above, we are vastly overestimating the cooling sensitivity of the building. This is what I'm trying to correct. Until we have those limits in place, I'm guessing we're more likely to end up with huge or non-physical beta hdd/cdd parameters that are fit to noise rather than signal, and worse models overall.

Do you have an alternative? I think you are advocating for less strict bounds? And I think that the solution you mentioned with temp means is actually stricter than what I'm proposing, so maybe we are in agreement at this point.

**Comment by danrubado** [comment]
This seems like a rational improvement for reducing the extreme balance point temperature selection that sometimes occurs. Testing should reveal how well it works and how well the heating/cooling loads are modeled. But avoiding the example you cited in the issue seems important.

**Comment by philngo-recurve** [comment]
Closing stale issue in preparation for new working group
