### ISSUE TITLE
CalTRACK Issue: Modifications to the Temperature Variable

### ISSUE THREAD

**Issue by jkoliner** [CalTRACK-2/caltrack#134]
### Prerequisites

* [X] Are you opening this issue in the correct repository (caltrack/grid/seat)?
* [X] Did you perform a search of previous Github issues to check if this issue has been previously considered?
(Addressed in issues #124 and #111, which can be rolled into this scan if approved)

Articles #s: 3.1, 3.3, 3.9

### Description

For billing, daily, and hourly methods, the current models use temperature or HDD/CDD. While unmodified temperature variables are highly correlated with the energy use of HVAC systems, there are a few modifications to the temperature variables that are readily tested using available data and could potentially lead to further reductions in residual variance. In other words, they may be more appropriate for representing the dynamics of outdoor heat penetrating the building shell. In modeling thermostat data, I have seen average out-of-sample CVRMSE reductions of up to 15-20% at the site level from these modifications, so I am curious whether they will have a similar impact on the daily or hourly methods for CalTRACK.

The two modifications I propose are:

- **Lagged rolling averages for temperature or HDD/CDD**: Heat takes time to penetrate the building shell. Especially for hourly calculations (e.g. HDH/CDH in Issue #120), averaging the previous 2-3 hours can mitigate the impact of spikes and dips on assumed usage, and align the temperature variable with actual consumption. A heat build-up term with a weight to prior temperatures that decays with time difference (e.g. 100% for t, 75% for (t-1), 75%^2 for (t-2), etc.) should also be tried.
- **Incorporation of relative humidity for a heat index and wind for wind chill**: Although much of the work for heat indices (a.k.a. sultriness indices) revolves around their application for humans or animals, HVAC systems do work harder to get rid of heat when it is hot and humid, and a heat index term has consistently beaten dry bulb temperature in my modeling of whole building energy use. I have had some success with using wind chill, although I don't think it would work as well for C&I.

### Proposed test methodology

1. Use a test C&I data set and a test residential data set
2. Build alternate formulations for temperature in place of dry-bulb temperature
a. 1 to 6 hour lags, inclusive and exclusive of current temperature
b. A couple heat build-up specifications
c. A couple specifications for relative humidity (e.g. from https://journals.ametsoc.org/doi/pdf/10.1175/1520-0450%281979%29018%3C0861%3ATAOSPI%3E2.0.CO%3B2) and wind chill.
3. Calculate CDD and HDD off of modified temperature variables
4. In-sample and out-of-sample testing of CalTRACK methods using the modified variables

### Acceptance Criteria

Demonstrated reduction of in-sample and out-of-sample CVRMSE and/or bias (i.e. not harming either while improving at least one)

**Comment by steevschmidt** [comment]
I'd like to support the first modification (Lagged rolling averages for temperature or HDD/CDD) but would suggest this could be analyzed as part of the more general issue #124.

**Comment by jkoliner** [comment]
I believe that this method would be applied to hourly temperatures, but apply to both hourly and daily methods, and deals more with short term conduction of heat through the building shell. As far as I understand it, #124 is much longer term. Is that not the case?

**Comment by steevschmidt** [comment]
@jkoliner: True; but #124 targets the same offset between temperature changes and energy changes. If we were to  confirm a significant impact from daily variations via that issue, perhaps the same setup & approach & testing might be shared with this issue? Also, we're not aware of anyone getting paid yet based on the hourly methods so perhaps this finer detail is not as urgent (?).

**Comment by danrubado** [comment]
At the very least, this seems very related to #124 and maybe should be handled together with the same general approach.

**Comment by jkoliner** [comment]
You keep this flurry of commenting up and I'm gonna nominate you for Chair for next year!

- Jon

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by philngo-recurve** [comment]
Closing stale issue in preparation for new working group
