### ISSUE TITLE
CalTRACK Issue: GRID Crossover Parking Lot

### ISSUE THREAD

**Issue by jkoliner** [CalTRACK-2/caltrack#135]
### Prerequisites

* [X] Are you opening this issue in the correct repository (caltrack/grid/seat)?
* [X] Did you perform a search of previous Github issues to check if this issue has been previously considered?

### Description

There was some discussion at the GRID working group about CalTRACK data cleaning and preparation procedures acting as the base for GRID procedures. This issue will serve as a parking lot to note modifications _within_ the CalTRACK methods, although not necessarily impacting CalTRACK, that are introduced by GRID. Because there are potential changes that GRID could introduce, this issue will allow them to be formally acknowledged by the CalTRACK working group.
- In some cases, GRID will diverge from CalTRACK within the current methods and we may need to specify GRID-only/CalTRACK-only steps.
- In other cases, GRID and CalTRACK needs may not be mutually exclusive and we may wish to modify the procedural instructions (e.g. ordering or terminology) if there is no impact on CalTRACK.
- Finally, GRID issues may bring to light improvements to the CalTRACK methods. These can be noted here, but should ultimately result in their own CalTRACK issues.

### Acceptance Criteria

Any issues that would modify the CalTRACK methods should be voted on as a separate issue and approved by the Working Group.

**Comment by philngo-recurve** [comment]
Closing stale issue in preparation for new working group
