### ISSUE TITLE
Methodology that uses monthly data directly, with an adjustment for variable billing cycle lengths

### ISSUE THREAD

**Issue by hshaban** [CalTRACK-2/caltrack#67]
Caltrack handles monthly data by apportioning monthly usage to daily values, then fitting regression models to the daily data. To reduce data processing and computational burden, we would like to consider a methodology that uses monthly data directly, with an adjustment for variable billing cycle lengths.

We propose to include a monthly model specification (hdd, cdd, intercept terms) that uses monthly data directly. Monthly usage is divided by the number of days in billing cycle before fitting the model, to yield average usage per day in each billing period.

**Comment by danrubado** [comment]
Agreed. Using the daily average energy usage for each monthly observation is a better way to handle the variable billing cycle length issue. It preserves the original form of the data and the real number of observations in the time series.

**Comment by hshaban** [comment]
**Proposed test methodology:**
* Caltrack monthly models will be fit to the baseline period usage data. These models convert billing data to daily values and fit a model to the daily data.
* A second model will be fit to the same data, but will include as independent variables: 
  * usage per day (i.e. usage during a billing period / number of days during that billing period) 
  * average degree days (i.e. total degree days during a billing period / number of days during that billing period)
* Model fit statistics will be calculated on the reporting period data (out of sample) for all buildings, yielding two sets of building-level model fit statistics: one for the default modeling method and the second for the new method.

**Acceptance criteria:**
* Model fit statistics for the two approaches will be pairwise compared using a statistical test (e.g. paired t-test). If differences in model fits between the two approaches are deemed to be due to chance (i.e. p>0.1), then the new method will be added to the Caltrack monthly spec as an alternative modeling approach for billing data.

**Comment by bkoran** [comment]
Using daily average energy use for each billing period requires a weighted regression or an optimization routine to avoid model bias when converting back to the billing period length.  This is pretty easy, so I am unclear why the "monthly" usage was converted to daily values.

**Comment by mcgeeyoung** [comment]
@bkoran This is right. I'm going to try to dig up the CalTRACK 1.0 discussion to recall the specifics of what we considered.

**Comment by hshaban** [comment]
## RESULTS

**Background**
Modeling using billing data was underspecified in Caltrack 1 (availability of daily data was assumed for the default methods).

**Recommendations**
We are proposing the following method for using billing data be clarified in the Caltrack specification. 

- Calculate the number of days in each billing period _n_.
- Calculate the average usage per day (UPD) in each billing period. This is calculated by dividing the total usage during the billing period by _n_.
- Calculate the average degree days per day during each billing period. This requires aggregating individual degree days for the entire billing period then dividing by _n_. 
- Use weighted least squares regression when fitting candidate models. Pass the daily average usage and degree days as the independent variables and use the corresponding _n_ as the weight for each billing period.

**Comment by bkoran** [comment]
Excellent.  FWIW, an alternate approach that could be useful depending upon how things are implemented is to use the independent variables as described, and use a minimization routine to minimize RMSE while requiring the monthly bias be zero.  Monthly bias being the bias estimated after converting the modeled kWh/day back to monthly billing periods by multiplying by n.  I mention this because a minimization routine may be implemented for interval models.

**Comment by rsridge** [comment]
Technically you're not estimating a _weighted least squares_ regression but only weighting each daily observation with the number of days in the billing cycle. Correct?

**Comment by hshaban** [comment]
We're recommending using weighted least squares with the number of days _n<sub>i</sub>_ as the corresponding weights for each billing cycle _i_. This is equivalent to using each daily observation _n<sub>i</sub>_ times in the regression.

**Comment by rsridge** [comment]
Hi Hassan,

 

MY only concern was with the use of the words “weighted least squares” which is normally associated with addressing the problem of heteroskedasticity.

 

Regards,

 

Rick

**Comment by hshaban** [comment]
Good point, Rick. Weighted least squares is typically used to deal with heteroscedasticity, but in that case the weights are set as 1/variance (or some proxy for that). I don't think there's a limitation on the weights you can use with generalized weighted least squares and, on the other hand, some software packages offer WLS just by adding a `weights` argument to an OLS function. Overall, I agree with you that we should be clear with terminology in the actual Caltrack specification. I'll clarify in the documentation that we are referring to a regression that is carried out with number of billing period days as the weights, not the (sometimes default) regression used to deal with heteroscedasticity.

**Comment by rsridge** [comment]
Thanks, Hassan.

 

-Rick

**Comment by hshaban** [comment]
This update has been integrated in CalTRACK 2. Closing this issue
