### ISSUE TITLE
Variable Degree Days for monthly models

### ISSUE THREAD

**Issue by hshaban** [CalTRACK-2/caltrack#69]
Caltrack monthly models use fixed balance point temperatures (60 and 70 F, for heating and cooling, resp.). 

We propose allowing a grid search procedure similar to the daily methods, that identifies the balance points which result in the best model fit.

**Comment by danrubado** [comment]
Agreed.

**Comment by hshaban** [comment]
**Proposed test methodology:**
* Caltrack monthly models will be fit to the baseline period usage data using fixed balance point temperatures.
* The fitting process will be repeated with a search grid for the balance point temperatures (search grid range determined by https://github.com/CalTRACK-2/caltrack/issues/72).
* Error metrics (CVRMSE and NMBE) will be calculated for each model using both approaches, using 12 months of reporting period data.

**Acceptance criteria:**
* This updated will be accepted into the Caltrack spec if allowing a balance point search grid does not cause average model performance to deteriorate (e.g. average model fit improves or paired t-test of model fit metrics shows no significant difference).

**Comment by hshaban** [comment]
## TEST RESULTS
**Dataset**
Electricity and gas billing data from approximately 1000 residential buildings that had undergone home performance improvements in Oregon.

**Tested parameters**
Base model using fixed degree day balance points (60 F for heating and 70 F for cooling) and a variable balance point range were tested (40-70/60-90).

**Results**
For the 1077 buildings tested using fixed balance points, 479 had been fit using intercept-only models, compared to 357 intercept-only models using variable balance points. This clearly indicates that buildings with weather-sensitive energy usage may be missed if the balance point temperature is restricted.

The remaining 598 buildings that had been fit using weather-sensitive models using both fixed and variable balance points, all saw improved model fits as captured by the model R-squared (mean R-squared 0.480 using fixed balance point vs. 0.495 using variable balance points). Figure 1 shows that some model fits remained almost unchanged, however, most model fits improved (in some cases, quite drastically).

![image](https://user-images.githubusercontent.com/13769526/36859786-4c3c54f6-1d34-11e8-8c9c-7366746ffb1d.png)
**Figure 1.** Comparison of model fits using fixed and variable degree day balance points.


**Recommendations**
Using a fixed balance point temperature may lead to reverting many buildings to an intercept-only model and overall, the model fits for other buildings are poorer. Therefore, we recommend using variable degree day balance points for billing models. Search range for optimal balance point to be determined in Issue #72.

**Comment by hshaban** [comment]
This update has been integrated in CalTRACK 2. Closing this issue
