### ISSUE TITLE
Documentation - disambiguate the term "month"

### ISSUE THREAD

**Issue by philngo** [CalTRACK-2/caltrack#78]
The methods often use the term "months" in an ambiguous way. As far as I can tell, there are three separate usages of the term "month", which need disambiguation in the documentation.

- **Month as period of time.** (e.g., "12 months") when describing periods of time. For clarity, it is probably better to use a better-defined unit, such as days ("12 months" -> "365 days"). A "month" is an ambiguous unit, as months vary in length. If the intention is that  so that there less ambiguity.12 months is a 365 day period, then my suggestion is that the documentation should just read "365 days".
- **Month as calendar month.** If month means calendar month, I suggest that the term "calendar month" be used. This is a pattern already sometimes present in the documentation.
- **Month as billing period.** Sometimes the term "month" is sometimes used to refer to a billing period, which is confusing because billing periods rarely align perfectly with calendar months, and sometimes are not even close (e.g., bi-monthly billing periods). My suggestion is to use the term "billing period" when this usage is intended. This ambiguity in usage extends even to the official name of the method - "CalTRACK Monthly Method".

**Comment by hshaban** [comment]
This update has been integrated in CalTRACK 2. Closing this issue
