### ISSUE TITLE
Documentation - clearer distinction between official data sufficiency reqs and test data prep.

### ISSUE THREAD

**Issue by philngo** [CalTRACK-2/caltrack#79]
The documentation describes steps used to clean and prepare the test data. This description indicates a set of data sufficiency requirements. It appears that some of these are intended to apply just to the test data preparation. If any are intended to apply more generally to the data sufficiency methods, these need to be clarified. One strategy for making this clearer is to make specification(s) for data sufficiency which are separate both from the test data preparation documentation and from the savings calculation and model/candidate model fitting specification (to the extent possible).

**Comment by hshaban** [comment]
This update has been integrated in CalTRACK 2. Closing this issue
