### ISSUE TITLE
Better specificity in data sufficiency requirements documentation.

### ISSUE THREAD

**Issue by philngo** [CalTRACK-2/caltrack#80]
In the monthly methods, the checks for sufficiency in the reporting period should only apply to annualized/weather normalized methods, and not to methods which use reporting period estimated or actual use. Stated another way, you should not need to know anything about the reporting period to fit a baseline model. The checks for sufficiency in the reporting period are of course necessary for annualized/weather normalized methods, because these methods also require fitting a reporting period model.

My suggestion is separately address baseline period data sufficiency and reporting period data sufficiency, then indicate carefully which methods require a baseline model only, or a baseline model and a reporting period model. I think this was the intention, but the docs are written in an ambiguous way.

**Comment by hshaban** [comment]
This update has been integrated in CalTRACK 2. Closing this issue
