### ISSUE TITLE
More than one heating and/or cooling coefficient can be needed

### ISSUE THREAD

**Issue by bkoran** [CalTRACK-2/caltrack#81]
The most obvious example for this on the residential side is a heat pump, and on the 2/15 call somebody (Steve Schmidt?)  mentioned another example of the equipment running out of capacity, and hence running continuously rather than an increasing run time as it gets colder.  There are 6 different slope regimes that are reasonable, not including a flat slope for the deadband between heating and cooling, with only one of these unlikely for residences.  Obviously these can't all be considered with monthly data, some of them won't be visible with monthly data, and fortunately only a few will be applicable to any individual building.  But good models may need more than a single heating and/or cooling coefficient.

**Comment by bkoran** [comment]
No comments on this?  I reiterated this in the Last Call for Monthly and Daily Issues.

**Comment by bkoran** [comment]
No comments on this?  I reiterated this, with examples, for FINAL CALL FOR COMMENTS: Monthly and Daily Methods Updates

**Comment by mcgeeyoung** [comment]
I'd be interested in digging into the mechanics of how you would select multiple balance points. I think it's important to consider alongside the more conventional single balance point per heating and cooling model. Would you calculate a coefficient for each of your balance points? Would there need to be a minimum number of temperature/usage points in each term to qualify it? We decided to drop p value, would you need to bring that back? Would a p value of .10 or less be required for each term? Are there interaction effects? And how stable are these balance points over time? I could imagine that you might have summer/winter differences in the elbows, or in commercial facilities some variance in what conditions would trigger the additional consumption. Probably even more common would be a situation where the independent variable wasn't weather, but occupancy/production. In that case this type of adjustment would be particularly important, but again, it sort of raises more questions than it answers.

**Comment by bkoran** [comment]
I'm just a lowly engineer, not a statistician or data scientist !  So consider many of my comments qualitatively...  
Yes, I estimate a coefficient for each of the change points.
Yes, I keep a minimum number of points in each line segment.
I calculate the t-statistic for each coefficient, rather than using p-value, but do check for significance.
Not sure what you mean by interaction effects.
Usually the change points are pretty stable over time with daily models, except they can change from baseline to post.  For hourly data, there are differences that I think are more due to building capacitance, but can appear as changes.
Occasional summer/winter differences, but pretty rare these days.  Was more common with manual controls in the past.
Except for industrial, weather is almost always the key independent variable, with occupancy sometimes important.
