### ISSUE TITLE
To improve support of seasonal energy variations, require baseline and reporting periods to cover the same seasons

### ISSUE THREAD

**Issue by steevschmidt** [CalTRACK-2/caltrack#93]
**Background**: Residential buildings have many events that increase or decrease energy use during different seasons: holiday lighting and/or visitors, pool pump runtimes, school years, athletic schedules, regular vacation dates, grow lights, etc. As a result, a home's non-HVAC energy use in February may be very different from December or July.

**Issue**: Current CalTRACK methods use a 12 month baseline period, but allows shorter reporting periods. Savings are calculated using a model created over the full 12 month period, but then applied to a shorter period covering one or more specific seasons. This approach can produce inaccurate savings results whenever there are seasonal or monthly variations in energy use during the reporting period. These inaccurate results may "even out" when the reporting period reaches a full 12 months, but since CalTRACK is used in P4P programs which pay monthly savings this effect can significantly impact savings calculations... and can be easily addressed.

Internally, HEA avoids this inaccuracy by always using a 12 month reporting period. This "rolling 12 month" reporting period may overlap with the baseline period, or be separated by it by several years (to monitor savings persistence). But by covering all seasons it provides an apples-to-apples comparison to a 12 month baseline period.  For example, a baseline period of January 2017 thru December 2017 might be compared to a reporting period of April 2017 thru March 2018; in this example 9 months of actual energy use will appear in both the baseline and reporting periods, so the savings calculation will be based only on the 3 months that are unique to each period.

Another possible approach is to select a shorter baseline period that covers the same calendar period as the reporting period (e.g. January thru March 2017 compared to January thru March 2018). This approach may be preferred in cases with long or energy-intensive interventions.

**Validation**: We ran a simple test comparing default CalTRACK savings results to CalTRACK savings results when the reporting period was extended backward (into the baseline period) to cover a full 12 months. As a result of this single change, savings results changed an average of 20% for natural gas and 10% for electricity for a cohort of 84 homes in PG&E's territory.

**Requested CalTRACK change**: Update methods to always use baseline and reporting periods that cover the same seasons. From a coding perspective we believe this would be a simple update.

**Comment by steevschmidt** [comment]
[I tried to log this under "Existing Daily Methods Improvements" but couldn't figure it out.]

**Comment by mcgeeyoung** [comment]
Cool, thanks! I put it into the roadmap. Just as a side note, I love this idea of monthly models and would be interested to see some examples of differences in outputs.
