### ISSUE TITLE
Links in File List not working

### ISSUE THREAD

**Issue by mtham8** [CalTRACK-2/caltrack#96]
Hello, 

It looks likes the links in the File List section isn't working.

See: [File List in Documentation](http://docs.caltrack.org/v1.0/data-prep/README/#file-list)

Would love to use these datasets to benchmark my implementation of CalTRACK's Energy Savings Estimation model.

Thanks,
Michelle

**Comment by hshaban** [comment]
The new CalTRACK documentation does not include test datasets - there are several [sample consumption files](https://github.com/openeemeter/eemeter/tree/eemeter-2.0.0-alpha/eemeter/samples) that are shipped with the eemeter package which can be used for testing
